[tool.poetry]
name = "game-of-life"
version = "0.1.0"
description = ""
authors = ["Maud Gautier", "Ludwig Schubert"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
